### PR TITLE
Added minor .github changes

### PR DESCRIPTION
**Pull request by maxpearl**
I'm a Pipenv user, so I added Pipfiles. I also wanted git to ignore my testing directory.

### CODE REVIEW

**Comment by maxpearl** [comment]
I realize perhaps I should have added this to the Beta branch - it seemed you were working on master now. Let me know.

**Comment by rajatomar788** [comment]
The beta branch is actually for the new version i.e. v6. So I think rewritten files of the new version aren't compatible with the current master branch version i.e. v5.
Thats just silly naming mistake on my side. 

I was working the Beta branch since the current master branch doesn't have much to improve. 
So I think I should be pulling your request then creating a new Tag and then bringing the Beta branch as master.?? 
What do you think??  

P. S.  I live in +5:30 timezone so may be slow to respond.

**Comment by rajatomar788** [comment]
P. S.  Can you test that whether the the new master branch files are working as they should.  I am not near a pc for now.

**Comment by maxpearl** [comment]
Sorry this took me so long - I've been swamped. Master branch seems to work as they should so far. If I run into anything, I'll submit a ticket (or fix.)

**Comment by rajatomar788** [comment]
Okay

**Pull request merged**
