### PR TITLE
adds ability to toggle multithreading

### PR DESCRIPTION
**Pull request by davidwgrossman**
Multiple users have reported that multithreading can be buggy. This PR disables multithreading by default.

### CODE REVIEW

**Comment by rajatomar788** [comment]
Why it is failing page saving tests?

**Comment by rajatomar788** [comment]
Please resolve conflicts

**Comment by davidwgrossman** [comment]
@rajatomar788 apologies. I believe I shared the PR before tests completed running.

**Comment by davidwgrossman** [comment]
@rajatomar788 hmm the tests are failing locally too

**Comment by rajatomar788** [comment]
With version 7 you can enable or disable multithreading easily. So I guess it settles the debate with a note that you should always set the thread join timeout value otherwise it will hang just like previously.

**Pull request closed without merging**
