### PR TITLE
elements.py: stash quotes/apostrophes for enquoted urls

### PR DESCRIPTION
**Pull request by NickVeld**
Fixes many pretty strange consequent problems caused by interfering into the head and tail checks by the quotes

### CODE REVIEW

**Comment by NickVeld** [comment]
I do not know why there are 3 broken tests instead of usual 1. But all of them are with the same exception.

**Comment by NickVeld** [comment]
Any Ideas? Have you restarted them?

**Comment by rajatomar788** [comment]
Hey @NickVeld can you check whether this fix is still relevant to the new release version 7.

**Comment by NickVeld** [comment]
As I understand, in 7.0+ the quotes is just removed. In turn, this PR saves the quotes in the string after replacement.

**Comment by rajatomar788** [comment]
Hey @NickVeld 
Sorry for being this late but can you please check the relevance of this pr to the current version else this pr should be closed. Same for the other one I just closed .

**Comment by NickVeld** [comment]
Hey @rajatomar788 
Everything has changed a lot. Maybe the issue still persists but it cannot be fixed with this PR anyway :(

**Pull request closed without merging**
