### PR TITLE
configs.py: fix log_file

### PR DESCRIPTION
**Pull request by NickVeld**
default value, check in is_set, ordering with debug

### CODE REVIEW

**Review by rajatomar788 — CHANGES_REQUESTED** [review]
It has merge conflicts I don't know why.

**Comment by NickVeld** [comment]
The conflicts have been resolved.

And I do not know what is wrong with the windows-3.8 testing. Maybe is it not stable?

**Comment by rajatomar788** [comment]
Yeah all the tests came out fine.

**Review by rajatomar788 — COMMENTED** [review]
Yep it should be helpful when resuming tasks.

**Pull request merged**
